修复ConvertFromUtf16BEBytesToUtf8BOMBytes方法
lc6464/LC6464.Base16384 pull request #4
Opened 2023-09-10 07:56 UTC by execute233

用一种简单粗暴的方式让它带上BOM了

2023-09-13 14:32 UTC, lc6464 requested changes
@execute233

2023-09-13 14:32 UTC, lc6464 commented on Text.cs
> +		return new ReadOnlySpan<byte>(result);
我觉得 L25 和 L26 肯定可以优化，另外就是这个 BOM 应该提取出来。

2023-09-13 14:32 UTC, lc6464 commented on Text.cs
> +		var temp = Encoding.Convert(Encoding.BigEndianUnicode, new UTF8Encoding(), data.ToArray());
```suggestion
		var temp = Encoding.Convert(Encoding.BigEndianUnicode, Encoding.UTF8, data.ToArray());
```

2023-09-13 14:39 UTC, lc6464 commented
DeepSource Transformers 没权限啊 @execute233
https://github.com/lc6464/LC6464.Base16384/pull/4/checks?check_run_id=16757499284

2023-09-13 15:25 UTC, lc6464 commented
放弃这个 PR 了。
详见 aa5a89951c65a19ee80ac50bac12a1d78dd491f4

2023-09-13 15:25 UTC, closed without merging

2023-09-16 05:22 UTC, execute233 commented
6